### ISSUE TITLE
error[E0432]: unresolved import `syn::token::CustomKeyword`

### ISSUE THREAD

**Issue by tlkahn** [LayerXcom/zero-chain#126]
When I ran  `cargo install --force --path ./` to build, I ran into the following error:

```
error[E0432]: unresolved import `syn::token::CustomKeyword`
  --> ~/.cargo/git/checkouts/substrate-69260aa4cd850e18/2cdae73/srml/support/procedural/tools/src/syn_ext.rs:26:5
   |
26 | use syn::token::CustomKeyword;
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^ no `CustomKeyword` in `token`

error: aborting due to previous error
```

I follow the instructions from https://layerxcom.github.io/zerochain-book/ch01-01-installation.html.  Can anyone help take a look?

**Comment by osuketh** [comment]
It looks some dependencies are broken now. You can fix it by `cargo update -p syn --precise 0.15.29`, then try `cargo install --force --path ./` again. I'll add some patches for fixing it, thanks!

**Comment by tlkahn** [comment]
Thanks for the quick response. I also checked and found out of sync between substrate and syn: https://github.com/paritytech/substrate/issues/2326.  Yes please fix since I am a fresh install and I suppose more devs will run into the same situation.

> The recent release (0.15.32) of syn removed the CustomKeyword trait which we are using here.

**Comment by osuketh** [comment]
This issue is fixed in the current master branch.
