### ISSUE TITLE
Compiled file in repository

### ISSUE THREAD

**Issue by djKooks** [LayerXcom/zero-chain#156]
Hello~first in project. Nice to meet you.
When project builded, seems compiled file is indicated as changed file in git repository.
```
modified:    runtime/wasm/target/wasm32-unknown-unknown/release/zerochain_runtime_wasm.compact.wasm
```
Would this needed to be removed?

**Comment by osuketh** [comment]
Hi. It doesn't need to be removed. Something wrong with it?

**Comment by djKooks** [comment]
@osuketh oh, no. Just because modified file always occurs after build.
If there is some reason to keep this in repository, it is fine. But seems better to ignore this file...

**Comment by osuketh** [comment]
Ah, it would be better. I'll fix it. Thanks for pointing out.

**Comment by NoCtrlZ** [comment]
This phenomenon occurred on my environment too and the reasoning is that git track the warm file in `runtime/wasm/target` directory.
I fixed it with [this commit](https://github.com/LayerXcom/zero-chain/pull/159)

**Comment by kination** [comment]
@osuketh @NoCtrlZ Seems okay to close~
