### ISSUE TITLE
[Zero Chain Book]Found some spell missings in ZeroChian tutorial.

### ISSUE THREAD

**Issue by NoCtrlZ** [LayerXcom/zero-chain#157]
Hi @osuketh 
I found some spell missings in [ZeroChain Book](https://layerxcom.github.io/zerochain-book/ch01-02-tutorial-confidential-payment.html).

1.2 & 1.3 Turotial -> Tutorial

![スクリーンショット 2019-12-23 21 28 02](https://user-images.githubusercontent.com/39494661/71358275-cf9d4200-25cb-11ea-83d0-38ebb3ffc22f.png)

Thank you.

**Comment by ashWhiteHat** [comment]
I created PR of this issue.
Please confirm.
https://github.com/LayerXcom/zerochain-book/pull/4

**Comment by osuketh** [comment]
Just merged it. Thanks.
